spring:
  application:
    name: eurekaclient
    port: 8000
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: ${spring.cloud.client.ip-address}
    lease-renewal-interval-in-seconds : 10
    lease-expiration-duration-in-seconds : 5
    prefer-ip-address: true
    instance-id : ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
